### ISSUE TITLE
check_cart返回参数错误

### ISSUE THREAD

**Issue by LongchuanYu** [jozhn/ddmc.monitor#11]
{'success': False, 'code': 1, 'msg': '参数错误', 'data': [], 'tradeTag': 'success', 'server_time': 1649842991, 'is_trade': 1}
请求异常!

**Comment by Acharlie00** [comment]
同样问题，有知道怎么解决的嘛？

**Comment by LongchuanYu** [comment]
> 同样问题，有知道怎么解决的嘛？

我做了如下改动和尝试，正常了:
1. 我把raw_body重新组织成dict的形式
   body = {
        "uid": uid,
        "longitude": longitude,
        "latitude": latitude,
        "station_id": station_id,
        "city_number": '0101',
        "api_version": api_version,
        "app_version": build_version,
        "applet_source": '',
        "channel": 'applet',
        "app_client_id": '4',
        "sharer_uid": '',
        "openid": device_id,
        "h5_source": '',
        "device_token": '',  # 必填
        "address_id": '',  # 必填
        "products": '',  # 必填
        "group_config_id": '',
        "isBridge": 'false'
    }
2. 猜测购物车需要有可购买的东西才能查询reverse_time

**Comment by Acharlie00** [comment]
> 

![图片](https://user-images.githubusercontent.com/76723714/164173167-01726d14-4fa3-4f15-8931-405f8ff45641.png)
就config.py里改成这样嘛？

**Comment by LongchuanYu** [comment]
更新了一下dict，试试能不能成功。

**Comment by Acharlie00** [comment]
> 更新了一下dict，试试能不能成功。
你那个太复杂了，还要装nginx，windows小白搞不定啊

**Comment by LongchuanYu** [comment]
可以尝试用api.py这个文件，我封装好了的。
