### ISSUE TITLE
都配置了但是还是报错 能正常请求 三味药以用

### ISSUE THREAD

**Issue by a1013329145** [jozhn/ddmc.monitor#12]
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.day.app', port=443): Max retries exceeded with url: 
import urllib3
urllib3.disable_warnings()
pip install cryptography 

pip install pyOpenSSL

pip install certifi
verify=False

**Comment by jozhn** [comment]
你这个是因为开了代理吧，跑脚本的时候要把fiddler关掉。
另外requests本来就支持verify=Flase啊
