### ISSUE TITLE
库存监控check_stock方法中json文件转换报错，麻烦大大瞅瞅

### ISSUE THREAD

**Issue by zorroforever** [jozhn/ddmc.monitor#13]
代码报错在这里json load的时候

>  with open("all_categories_formatted.json") as f:
        flag = False
        all_categories = json.load(f)
错误信息如下
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 38: illegal multibyte sequence
感觉是商品列表的json有问题，但是我查了一下json格式是没有问题的。
PS：购物车监控运力运行良好 谢谢大大啦。

**Comment by jozhn** [comment]
@sqvktfet 老哥能看看吗

**Comment by LibraWind255** [comment]
with open("all_categories_formatted.json",encoding='utf-8') as f: 亲测可行

**Comment by jozhn** [comment]
> with open("all_categories_formatted.json",encoding='utf-8') as f: 亲测可行

感谢 

https://github.com/jozhn/ddmc.monitor/commit/1e4a9e2dd28bce2c5ccc6e9be561c40bc1e96f63
