### ISSUE TITLE
返回<Response [405]>怎么解决

### ISSUE THREAD

**Issue by ok123now** [jozhn/ddmc.monitor#3]
def check_home():
    url = 'https://maicai.api.ddxq.mobi/homeApi/newDetails'
    payload = {'api_version': '9.49.1',
               'station_id': config.station_id,
               }
    r = requests.get(url, params=payload)

返回<Response [405]>怎么解决

**Comment by Alimanman** [comment]
同样的问题，405
大佬谢谢~

**Comment by xiaoxyzero** [comment]
同405 求解

**Comment by jozhn** [comment]
叮咚更新了策略，这里加上header，header里加UA就行了

**Comment by jozhn** [comment]
已修复 https://github.com/jozhn/ddmc.monitor/commit/08b47df2c2ad76c3db414730193eaef3a21f1b0f
